# # .github/workflows/ci_cd_pipeline.yml
# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.8'

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt

#     - name: Run unit tests
#       run: |
#         pytest

#     - name: Train model
#       run: |
#         python scripts/train.py

#     - name: Save model artifact
#       uses: actions/upload-artifact@v3
#       with:
#         name: logistic_regression_model
#         path: models/logistic_regression_model.pkl

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     if: github.ref == 'refs/heads/main'

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.8'

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt
#         pip install boto3  # AWS SDK for Python

#     - name: Download model artifact
#       uses: actions/download-artifact@v3
#       with:
#         name: logistic_regression_model
#         path: models/logistic_regression_model.pkl

#     - name: Deploy model to S3
#       run: |
#         python scripts/deploy.py